import { Grid, Box, Paper} from '@mui/material'
import Head from 'next/head'
import { useState } from 'react'
import Main from '../components/main'
import SideBarLeft from '../components/sideBarLeft'
import SideBarRight from '../components/sideBarRight'




export default function Home() {
  const [user, setUser] = useState({})
  return (
    <Box sx={{flexGrow: 1}} style={{margin: 20}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Grid container spacing={2} >
          <Grid item xs={12} md={3}>
          <SideBarLeft user={user}/>
          </Grid>
          <Grid item  xs={12} md={6}>
            <Main/>
          </Grid>
          <Grid item  xs={12} md={3}>
          <SideBarRight setFunc={setUser} />
          </Grid>          
        </Grid>
        
       
    </Box>
  )
}
